-- DEPRECATED: do not run this script.
-- The policies here were replaced by the restricted staging schema in supabase_schema.sql.
-- That schema is for a clean homologation project only; production needs a reviewed migration.
